### ISSUE TITLE
Photos don't show until after photoUpdateInterval

### ISSUE THREAD

**Issue by dkgoodman** [miccl/MMM-Random-local-image#6]
Photo doesn't show up until after the photoUpdateInterval has expired. A fix is to create a var named loaded in the start function, initialized to false, and then add the code below after this.imageLoadFinished = true;

      if ( !this.loaded ) // if first time, show photos we just loaded
        this.updateDom();
      this.loaded = true;

**Comment by miccl** [comment]
Hi @dkgoodman,

nice finding. I have not noticed this on my mirror.
Do you want to create a PR to fix it like you mentioned?

Greets
Michael

**Comment by dkgoodman** [comment]
Maybe mine is different because it's running on Windows? I'm have to try it on the raspberry. I've never checked anything in to GitHub. This is the first issue I've reported, too. I'm still tweaking the code. So far I've added a grayscale option. I  wrote my own version of this module before I found yours, but I had the photo names hard coded in an array. I like your way of reading the folder contents better.

**Comment by miccl** [comment]
It could be a windows problem or I just don't catch it. I think its probably the latter 😄
If you never did it, it is a good practice for you. Looking forward to your pull request!

**Comment by donaldjohansen** [comment]
Can someone give me a more detailed description on how to fix the update Interval? Not really understanding  fix is to create a var named loaded in the start function, initialized to false, and then add the code below after this.imageLoadFinished = true;

I sort of get adding the code just not exactly shore where? Not understanding how to create a var?

Thanks,

Don

I thought my file location was an issue because the images weren't loading. Turned out I didn't wait long enough becuase of the  photoUpdateInterval didn't expire before I quit the app.

**Comment by miccl** [comment]
Created a branch with the fix: https://github.com/miccl/MMM-Random-local-image/pull/9
Sadly i cant test this anytime soon, because i dont have my magic mirror near me.
@donaldjohansen @dkgoodman can you please check, if that fixes it. Just check the branch out with `git checkout miccl-fix-initialization`

**Comment by miccl** [comment]
seems to be working :) closing this issue
